version: '3'
services:
  database:
    ports:
     - "5000:5432"
    image: "debezium/postgres:11-alpine"
  
  intueri-detector:
    build:
      context: .
      dockerfile: docker/detector.Dockerfile
    depends_on:
      - kafka
      - zookeeper

  intueri-orchestrator:
    build:
      context: .
      dockerfile: docker/orchestrator.Dockerfile
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8010:8010"

  intueri-output:
    build:
      context: .
      dockerfile: docker/output.Dockerfile
    depends_on:
      - kafka
      - zookeeper

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
    - zookeeper
    ports:
    - 9092:9092
    - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://192.19.0.4:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
